console.log('hello, world');
var $heading = document.querySelector('h1');
console.log('$heading', $heading);
console.dir(document.querySelector('h1'));
var $explanation = document.querySelector('p#explanation');
console.log('$explanation', $explanation);
console.dir(document.querySelector('p#explanation'));
var $hint = document.querySelector('p.hint');
console.log('$hint', $hint);
console.dir(document.querySelector('p.hint'));
var $paragraphs = document.querySelectorAll('p');
console.log('$paragraphs', $paragraphs);
var $links = document.querySelectorAll('.example-link');
console.log('$link', $links);
